import { Pool } from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { DuplicateMacAddressError } from "@/modules/stations/errors/duplicate-mac-address.error.js";
import { PgStationRepository } from "@/modules/stations/repositories/pg-station.repository.js";

// Testes de integração do repositório Postgres. Rodam só quando
// TEST_DATABASE_URL aponta para um Postgres descartável (o CI sobe um).
// Tudo acontece num schema próprio, apagado no fim: nunca toca tabelas reais.
const TEST_DATABASE_URL = process.env.TEST_DATABASE_URL;
const SCHEMA = `it_stations_${process.pid}`;

describe.skipIf(!TEST_DATABASE_URL)(
  "PgStationRepository (Postgres real)",
  () => {
    let pool: Pool;
    let repository: PgStationRepository;

    const station = (n: number) => ({
      property_id: 1,
      mac_address: `AA:BB:CC:DD:EE:${String(n).padStart(2, "0")}`,
      name: `Estação ${n}`,
      latitude: -23.5,
      longitude: -46.6,
    });

    beforeAll(async () => {
      const admin = new Pool({ connectionString: TEST_DATABASE_URL });
      await admin.query(`DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE`);
      await admin.query(`CREATE SCHEMA ${SCHEMA}`);
      await admin.query(`
      CREATE TABLE ${SCHEMA}.properties (id integer PRIMARY KEY);
      INSERT INTO ${SCHEMA}.properties (id) VALUES (1);
      CREATE TABLE ${SCHEMA}.stations (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        property_id integer NOT NULL REFERENCES ${SCHEMA}.properties (id),
        mac_address varchar(50) NOT NULL,
        name varchar(100) NOT NULL,
        latitude decimal(10,8) NULL,
        longitude decimal(11,8) NULL,
        last_communication_at timestamp NULL,
        created_at timestamp NOT NULL DEFAULT current_timestamp,
        CONSTRAINT stations_mac_address_unique UNIQUE (mac_address)
      );
    `);
      await admin.end();

      pool = new Pool({
        connectionString: TEST_DATABASE_URL,
        options: `-c search_path=${SCHEMA}`,
      });
      repository = new PgStationRepository(pool);
    });

    beforeEach(async () => {
      await pool.query("TRUNCATE stations RESTART IDENTITY");
    });

    afterAll(async () => {
      await pool?.query(`DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE`);
      await pool?.end();
    });

    it("should_keep_the_real_total_when_page_is_beyond_the_last", async () => {
      for (let n = 1; n <= 3; n += 1) await repository.create(station(n));

      const result = await repository.findMany({ page: 5, limit: 2 });

      expect(result.data).toEqual([]);
      expect(result.total_records).toBe(3);
    });

    it("should_paginate_and_count_with_filter", async () => {
      for (let n = 1; n <= 3; n += 1) await repository.create(station(n));

      const result = await repository.findMany({
        page: 2,
        limit: 2,
        property_id: 1,
      });

      expect(result.total_records).toBe(3);
      expect(result.data.map((s) => s.id)).toEqual([3]);
      expect(typeof result.data[0]!.latitude).toBe("number");
    });

    it("should_return_zero_total_when_there_are_no_stations", async () => {
      const result = await repository.findMany({ page: 1, limit: 20 });

      expect(result).toEqual({ data: [], total_records: 0 });
    });

    it("should_translate_unique_violation_on_create_to_duplicate_mac_error", async () => {
      await repository.create(station(1));

      await expect(repository.create(station(1))).rejects.toBeInstanceOf(
        DuplicateMacAddressError,
      );
    });

    it("should_return_409_semantics_for_concurrent_creates_with_same_mac", async () => {
      const results = await Promise.allSettled([
        repository.create(station(7)),
        repository.create(station(7)),
      ]);

      expect(results.filter((r) => r.status === "fulfilled")).toHaveLength(1);
      const rejected = results.find((r) => r.status === "rejected");
      expect((rejected as PromiseRejectedResult).reason).toBeInstanceOf(
        DuplicateMacAddressError,
      );
    });

    it("should_translate_unique_violation_on_update_to_duplicate_mac_error", async () => {
      await repository.create(station(1));
      const second = await repository.create(station(2));

      await expect(
        repository.update(second.id, station(1)),
      ).rejects.toBeInstanceOf(DuplicateMacAddressError);
    });

    it("should_rethrow_other_database_errors_untouched", async () => {
      await expect(
        repository.create({ ...station(1), property_id: 999 }),
      ).rejects.toMatchObject({ code: "23503" });
    });
  },
);
